'use client';
import {useEffect,useState} from 'react';
export default function Admin(){const[logged,setLogged]=useState(false),[password,setPassword]=useState(''),[data,setData]=useState<any>(null),[pricing,setPricing]=useState<any>(null),[msg,setMsg]=useState('');
 const login=async()=>{const r=await fetch('/api/admin/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({password})});if(r.ok){setLogged(true);load()}else setMsg('Invalid admin password')};
 const load=async()=>{const [u,p]=await Promise.all([fetch('/api/admin/users'),fetch('/api/admin/pricing')]);if(u.ok)setData(await u.json());if(p.ok)setPricing(await p.json())};useEffect(()=>{load()},[]);
 const save=async()=>{const r=await fetch('/api/admin/pricing',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(pricing)});setMsg(r.ok?'Pricing saved.':'Could not save pricing.');load()};
 if(!logged)return <main><div className="wrap"><div className="card auth"><h1>Control Room</h1><p className="muted">Private administration</p><input className="input" type="password" placeholder="Admin password" value={password} onChange={e=>setPassword(e.target.value)}/><button className="btn" onClick={login}>Sign in</button>{msg&&<div className="status danger">{msg}</div>}</div></div></main>;
 return <main><div className="wrap admin"><nav className="nav"><div className="brand">GeoPram<span>Admin</span></div><span className="pill">PRIVATE</span></nav><h1>Users, payments & pricing</h1>{pricing&&<section className="card"><h2>Set payment amounts</h2>{pricing.tasks.map((t:any,i:number)=><div key={t.id} style={{display:'flex',gap:10,alignItems:'center',margin:'10px 0'}}><b style={{minWidth:300}}>{t.name}</b><input className="input" style={{margin:0}} type="number" value={t.price} onChange={e=>{const x={...pricing,tasks:[...pricing.tasks]};x.tasks[i]={...x.tasks[i],price:Number(e.target.value)};setPricing(x)}}/></div>)}<div style={{display:'flex',gap:10,alignItems:'center',margin:'10px 0'}}><b style={{minWidth:300}}>3-task bundle discount price</b><input className="input" style={{margin:0}} type="number" value={pricing.bundle.price} onChange={e=>setPricing({...pricing,bundle:{...pricing.bundle,price:Number(e.target.value)}})}/></div><button className="btn" onClick={save}>Save pricing</button>{msg&&<div className="status success">{msg}</div>}</section>}
 <section className="card" style={{marginTop:20}}><h2>Website users</h2><table><thead><tr><th>Email</th><th>Verified</th><th>Created</th><th>Total paid</th><th>Last paid</th></tr></thead><tbody>{data?.users?.map((u:any)=><tr key={u._id}><td>{u.email}</td><td>{u.verified?'Yes':'No'}</td><td>{new Date(u.createdAt).toLocaleString()}</td><td>KES {Number(u.totalPaid||0).toLocaleString()}</td><td>{u.lastPaidAt?new Date(u.lastPaidAt).toLocaleString():'—'}</td></tr>)}</tbody></table></section>
 <section className="card" style={{marginTop:20}}><h2>Transactions</h2><table><thead><tr><th>Reference</th><th>Email</th><th>Tasks</th><th>Amount</th><th>Status</th><th>Receipt/output email</th><th>Date</th></tr></thead><tbody>{data?.transactions?.map((t:any)=><tr key={t._id}><td>{t.reference}</td><td>{t.email}</td><td>{t.taskIds?.join(', ')}</td><td>KES {Number(t.amount).toLocaleString()}</td><td>{t.status}</td><td>{t.outputEmailed?'Sent':'Pending'}</td><td>{new Date(t.createdAt).toLocaleString()}</td></tr>)}</tbody></table></section></div></main>}
