'use client';
import {useState} from 'react';
export default function Home(){const[email,setEmail]=useState('');const[otp,setOtp]=useState('');const[step,setStep]=useState(1);const[msg,setMsg]=useState('');const[verified,setVerified]=useState(false);const[phone,setPhone]=useState('');const[pay,setPay]=useState('');const[pricing,setPricing]=useState<any>({tasks:[{id:'1',name:'Task 1 — Laikipia East Primary Schools Map',price:1000},{id:'2',name:'Task 2 — GIS Task Output',price:2000},{id:'3',name:'Task 3 — GIS Task Output',price:1500}],bundle:{name:'All 3 Tasks — Discount Bundle',price:3500}}); 
 const post=async(url:string,body:any)=>{const r=await fetch(url,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const d=await r.json();if(!r.ok)throw new Error(d.error||'Request failed');return d};
 async function request(){try{setMsg('Sending verification code…');await post('/api/auth/request-otp',{email});setStep(2);setMsg('OTP sent. Check your inbox.');}catch(e:any){setMsg(e.message)}}
 async function verify(){try{setMsg('Verifying…');await post('/api/auth/verify-otp',{email,otp});setVerified(true);setStep(3);setMsg('Email verified. Choose an output.');}catch(e:any){setMsg(e.message)}}
 async function payNow(selection:any){try{if(!phone)return setMsg('Enter the M-PESA phone number.');setPay('Initiating secure M-PESA prompt…');const d=await post('/api/payment/stkpush',{phone,selection});setPay(`Prompt sent. ${d.customerMessage||'Complete payment on your phone.'} Reference: ${d.reference}`)}catch(e:any){setPay((e as Error).message)}}
 return <main><div className="wrap"><nav className="nav"><div className="brand">GeoPram<span>Tasks</span></div><div className="muted">GIS outputs • Secure delivery</div></nav><section className="hero"><div><span className="eyebrow">PAY • VERIFY • DOWNLOAD</span><h1>Professional GIS task outputs, delivered securely.</h1><p>Verify your email for free, select the map/task output you need, pay by M-PESA and receive your receipt plus secure PDF/SVG delivery links.</p><p><b>Support:</b> 0702781490 · info@geopramtech.co.ke</p></div><div className="heroVisual"><div className="lock">🔒</div><div style={{color:'white',fontWeight:800,fontSize:26}}>Protected GIS files</div><p style={{color:'#dbeafe'}}>Paid PDF and SVG files are kept outside the public web folder. Access is unlocked only after successful payment confirmation.</p><div className="visualCard"><b>Fast delivery</b><br/><span className="muted">Receipt + output email after Daraja confirms payment.</span></div></div></section>
 <section className="card auth">{step===1&&<><h2>Verify your email — free</h2><p className="muted">We send a one-time 6-digit code. No payment is required to verify.</p><input className="input" type="email" placeholder="you@example.com" value={email} onChange={e=>setEmail(e.target.value)}/><button className="btn" onClick={request}>Send verification code</button></>}{step===2&&<><h2>Enter your OTP</h2><p className="muted">Code sent to <b>{email}</b>.</p><input className="input" inputMode="numeric" maxLength={6} placeholder="123456" value={otp} onChange={e=>setOtp(e.target.value)}/><button className="btn" onClick={verify}>Verify email</button></>}{step===3&&verified&&<><h2>Choose your GIS output</h2><p className="muted">Your email is verified. Payment is required before any PDF/SVG output becomes accessible.</p><div className="grid3">{pricing.tasks.map((t:any)=><div className="card task" key={t.id}><b>{t.name}</b><small>Secure PDF + SVG after successful payment.</small><div className="price">KES {Number(t.price).toLocaleString()}</div><button className="btn" onClick={()=>payNow([t.id])}>Pay & unlock</button></div>)}</div><div className="card" style={{marginTop:16}}><b>{pricing.bundle.name}</b><div className="price">KES {Number(pricing.bundle.price).toLocaleString()}</div><p className="muted">One payment unlocks all three tasks.</p><button className="btn alt" onClick={()=>payNow('bundle')}>Pay bundle & unlock all</button></div><input className="input" style={{marginTop:18}} placeholder="M-PESA phone e.g. 0712345678" value={phone} onChange={e=>setPhone(e.target.value)}/></>}{msg&&<div className="status">{msg}</div>}{pay&&<div className="status success">{pay}</div>}</section>
 <footer className="footer"><b>GeoPram Technologies</b><br/>Automated delivery. Please do not reply to verification/payment emails. For help: 0702781490 · info@geopramtech.co.ke</footer></div></main>}
