import nodemailer from 'nodemailer';
const transporter=()=>nodemailer.createTransport({host:process.env.SMTP_HOST,port:Number(process.env.SMTP_PORT||587),secure:Number(process.env.SMTP_PORT||587)===465,auth:{user:process.env.SMTP_USERNAME,pass:process.env.SMTP_PASSWORD}});
const from=process.env.SMTP_FROM || `GeoPram Tasks <${process.env.SMTP_USERNAME}>`;
const replyTo=process.env.SMTP_REPLY_TO || 'no-reply@geopram.com';
export async function sendOtp(email:string,otp:string){await transporter().sendMail({from,to:email,replyTo,subject:'GeoPram Tasks — verify your email',text:`Your GeoPram Tasks verification code is ${otp}. It expires in 10 minutes. Do not reply to this email.`,html:`<div style="font-family:Arial,sans-serif;max-width:600px;margin:auto"><h2>Verify your email</h2><p>Use this one-time code to access GeoPram Tasks:</p><div style="font-size:32px;font-weight:700;letter-spacing:8px;padding:20px;background:#eef5ff;border-radius:12px;text-align:center">${otp}</div><p>This code expires in 10 minutes.</p><p style="color:#64748b">This mailbox is not monitored. Please do not reply.</p></div>`});}
export async function sendReceiptAndOutputs(email:string,tx:any,pricing:any,links:{pdf:string,svg:string}[]){
 const tasks=tx.taskIds.map((id:string)=>pricing.tasks.find((x:any)=>x.id===id)).filter(Boolean);
 const rows=tasks.map((t:any)=>`<tr><td>${t.name}</td><td style="text-align:right">KES ${Number(t.price).toLocaleString()}</td></tr>`).join('');
 const linkHtml=links.map((l,i)=>`<div style="margin:18px 0"><b>Task ${tx.taskIds[i]} files</b><br/><a href="${l.pdf}" style="display:inline-block;background:#0b5cff;color:white;padding:11px 16px;border-radius:8px;text-decoration:none;margin:7px 6px 7px 0">Download PDF</a><a href="${l.svg}" style="display:inline-block;background:#0f172a;color:white;padding:11px 16px;border-radius:8px;text-decoration:none;margin:7px 0">Download SVG</a></div>`).join('');
 await transporter().sendMail({from,to:email,replyTo,subject:`GeoPram Tasks — payment receipt & outputs ${tx.reference}`,text:`Payment received. Reference: ${tx.reference}. Amount: KES ${tx.amount}. Your paid task PDF and SVG outputs are available from the secure links in this email. Do not reply.`,html:`<div style="font-family:Arial,sans-serif;max-width:680px;margin:auto"><h2>Payment successful</h2><p>Thank you. Your task outputs are now unlocked.</p><p><b>Receipt:</b> ${tx.reference}<br/><b>Amount paid:</b> KES ${Number(tx.amount).toLocaleString()}<br/><b>Status:</b> Paid</p><table style="width:100%;border-collapse:collapse">${rows}<tr><td style="padding-top:12px"><b>Total</b></td><td style="text-align:right;padding-top:12px"><b>KES ${Number(tx.amount).toLocaleString()}</b></td></tr></table><hr/>${linkHtml}<p style="color:#64748b">These links are signed and expire after 48 hours. This is an automated email; please do not reply.</p></div>`});
}
export async function sendPaymentInstructions(email:string,reference:string,amount:number){await transporter().sendMail({from,to:email,replyTo,subject:`GeoPram Tasks — payment initiated ${reference}`,text:`Payment request ${reference} for KES ${amount} has been initiated. Complete the M-PESA prompt. Do not reply.`,html:`<div style="font-family:Arial,sans-serif;max-width:600px;margin:auto"><h2>M-PESA payment initiated</h2><p>Check your phone and enter your M-PESA PIN to complete the payment.</p><p><b>Reference:</b> ${reference}<br/><b>Amount:</b> KES ${amount.toLocaleString()}</p><p style="color:#64748b">Do not reply to this automated email.</p></div>`});}
